id: IAB713972
legacy_id: P003142
ocr_import_info:
  bdrc_scan_id: W1PD181141
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T12:24:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T03:57:59.565844+00:00'
last_modified: 2022-09-01 11:58:06.091715
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD181141
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1PD181141
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྟའུ་སྦས་ཞབས་བྲག་དཀར་དང་གཡུང་དྲུང་བོན་རྫོང་གི་དཀར་ཆག
statistics:
  ocr_word_mean_confidence_index: 0.4950830564508782
  ocr_word_median_confidence_index: 0.46000000834465027
quality: null
bases:
  I1KG16290:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16290
      total_pages: 144
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16290.txt
    statistics:
      ocr_word_median_confidence_index: 0.46000000834465027
      ocr_word_mean_confidence_index: 0.4950830564508782
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
