id: P003142
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD181141
  title: རྟའུ་སྦས་ཞབས་བྲག་དཀར་དང་གཡུང་དྲུང་བོན་རྫོང་གི་དཀར་ཆག
  author: ''
  volumes:
    24171448faa140d486341edb86585ec8:
      image_group_id: I1KG16290
      title: ''
      volume_number: 1
      total_pages: 144
